# Generated by Django 5.0.3 on 2024-06-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "permissions": [
                    ("can_view_dashboard", "Can view dashboard"),
                    ("can_edit_projects", "Can edit projects"),
                    ("can_add_user", "Can add user"),
                ],
            },
        ),
    ]
