version: '3.9'

services:
  web:
    build: .
    command: gunicorn DevOps_Streamline.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=your_project_name.settings

  nginx:
    build:
      context: ./nginx
    ports:
      - "8002:80"  # Map port 8001 on the host to port 80 in the container
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  static_volume:
