version: '3'
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings

  apache:
    image: httpd:2.4
    depends_on:
      - web
    ports:
      - "$8001:80"
    volumes:
      - ./apache-config:/usr/local/apache2/conf
